### ISSUE TITLE
Files not being transfered

### ISSUE THREAD

**Issue by emil10001** [agarbato/unicloud#16]
I've got two separate machines on my local network that I'd like to get synced up together. The client is able to connect to the server, and all of the files are currently residing on the server, to be transferred to the client.

Here are the errors I'm getting:

```
[ 3660 ] Event Log
[ my-client ][ share1 ][ 2022-01-25 16:25:35 ][ 2022-01-25 16:25:35 ][ 0s ][ KO ]
Unison 2.51.3 (ocaml 4.13.0): Contacting server...
Permission denied, please try again.
Permission denied, please try again.
unison@my-server: Permission denied (publickey,password,keyboard-interactive).
Fatal error: Lost connection with the server
```

I'm confused about how the client is able to connect, but is unable to transfer files. When I attempt to run the ssh command manually, it gives me a challenge for a password, and I don't know what that is, or where to find it. That challenge seems like it may be causing the issue that I'm seeing reported above.

**Comment by agarbato** [comment]
Hi @emil10001 
If the client is able to reach the server it means that the port is open so it seems related to key not properly added to the authorized keys.
Did you complete the client registration? Do you see any message on the homepage or on the clients page?
When you activate a client its key is added to the authorized keys of the server.
On /data/.ssh/authorized_keys on the server you should see the client public key.
Make sure  to persist data volumes on both client and server.
Do you mind to share your docker-compose.yml file?
Maybe cleanup data folder on both server/client  (make sure to remove hidden files also) and start fresh using the docker-compose.yml provided on the repo.

**Comment by agarbato** [comment]
Just to give you more context.

On server /data/.ssh/unicloud_authorized_keys you should have the client key.
Something like this:

`command="/usr/bin/unison -server" ssh-rsa AAAAB3NzaC1yc2......= unison@aa210add955c CLIENT:testing-client1%`

On client /data/.ssh you should have both id_rsa and id_rsa.pub.
The pub key should match the one on authorized_keys but this is normally done automatically when you register the client.

If you clone the repo and run docker-compose up -d you can test it locally first.
The docker-compose.yml is already configured to persist volumes from the repo folders.

**Comment by emil10001** [comment]
**Updates at the top**

Re-registered the pub key for the client and now my errors are different:

```
[ 3776 ] Event Log
[ my-win-client ][ share1 ][ 2022-01-26 02:54:34 ][ None ][ Nones ][ KO ]
Sync was interrupted
```

**More info below**

Ah, that's helpful context, and I may try the cleanup step if I can't fix it another way. 

`Did you complete the client registration?` - Ok, while I had done the registration, and the client was reporting itself as connected, i checked the client's ssh pub key, and it was not in the server's unicloud_authorized_keys file. I'm not clear why it changed, but I was messing with the config a bit, and bouncing between which box was going to be the server. 

`Do you see any message on the homepage or on the clients page?` - homepage `All clients are registered`. Clients page is weird, one of the two clients is showing with a `Last Seen`, which is the one that matches the client name provided in my docker-compose file, but the one with a fake name where the key matches is not showing a `Last Seen`, but does have a `Join Date`. When I click on the client name for the one with the fake name and real key, [I get an error page](https://github.com/agarbato/unicloud/issues/17). 

`Make sure to persist data volumes on both client and server.` - what does this mean?

**Server** `docker-compose.yml` running on a physical Ubuntu machine with a bunch of other docker containers

```
version: '3.3'
services:
  # SERVER
  test_unicloud_server:
    image: agarbato1/unison-unicloud
    container_name: unison-server
    ports:
      - "2222:22"
      - "5001:80"
    environment:
      - USER=unison
      - USER_UID=1000
     # - USER_GIDS=33,14
      - SERVER_HOSTNAME=unicloud_testing_server
      - SERVER_UI_USERNAME=admin
      - SERVER_UI_PASSWORD=pass
      - SERVER_DEBUG=True
      - ROLE=SERVER
    networks:
      unison:
        aliases:
          - my-uni-server
    # added dns to get the container to resolve hostnames on my local network
    dns:
      - 192.168.1.1
    volumes:
      - type: bind
        source: /mnt/ssd1/misc/unison_data/server
        target: /data
      - type: bind
        source: /mnt/ssd1/misc/unison_data/server/shares
        target: /shares
      - type: bind
        source: /mnt/ssd1/media
        target: /shares/share1/my-srv/media
      - type: bind
        source: /mnt/ssd2/media2
        target: /shares/share1/my-srv/media2
networks:
  unison:
    driver: bridge
    ipam:
      driver: default
```

**Client** `docker-compose.yml` running on a physical Windows machine, inside an Ubuntu WSL2 environment with WSL2 enabled in docker

```
version: '3.3'
services:
  # CLIENT
  test_unicloud_client:
    image: agarbato1/unison-unicloud
    container_name: unison-client
    environment:
      - CLIENT_HOSTNAME=my-win-client
      - ROLE=CLIENT
      - USER=unison
      - USER_UID=1000
      # my-ubu-srv is the local hostname of the physical box the container is running on
      - SERVER_HOSTNAME=my-ubu-srv 
      - SERVER_PORT=2222 # needed to change this from default to get it to work
      - SERVER_SHARE=share1
      - SHARE_IGNORE=.git*|.idea|.unison|.DS_Store
      - API_PROTOCOL=http
      - API_PORT=5001 # needed to change this from default to get it to work
      - SYNC_INTERVAL=15
    restart: on-failure
    volumes:
      - type: bind
        source: ./local_tests/client
        target: /data
      - type: bind
        source: ./local_tests/client/share
        target: /data/share
      - type: bind
        source: /mnt/d/my-srv
        target: /data/share/my-srv
    networks:
      unison-client:
    # added dns to get the container to resolve hostnames on my local network
    dns:
      - 192.168.86.1

networks:
  unison-client:
    driver: bridge
    ipam:
      driver: default
```

**Comment by agarbato** [comment]
Hi again,

My suggestion is still to start fresh with a clean config since there might be some broken config around if you swapped client/server role between machines. I'll explain how to cleanup and then give you some more hints on how to troubleshoot the connection.  

**Before you start :**

On **client** docker-compose you have 3 volumes.
This is wrong.   You only need 2, one for the data volume and one for share data sync.
You should not change the target, **it must be /data/share**.
Source can be any path on your filesystem.
A client can only sync one share.

This should be ok:
```
volumes:
  - type: bind
    source: ./local_tests/client
    target: /data
  - type: bind
    source: /mnt/d/my-srv
    target: /data/share
```

**server** docker-compose volumes seems a bit confusing to me.
**When you add a share from the UI the path must match volume target.**
Final target can be created automatically or manually (see below)

I would change to something like this
```
volumes:
  - type: bind
    source: /mnt/ssd1/misc/unison_data/server
    target: /data
  - type: bind
    source: /mnt/ssd1/media
    target: /shares
  - type: bind
    source: /mnt/ssd2/media2/share2
    target: /shares/share2
```

The app can create destination folder when you add a share.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/2765876/151132175-142385f5-5027-416f-ac7c-2092af4f67e9.png">

This will result in /mnt/ssd1/media/share1 being created automatically
Generally speaking if you only have one media volume you just need 2 volumes on the server, one for data and the other for shares with target /shares, final paths will be created automatically.

Since you have a media on a different disk to add the 2nd share on ssd2 select 
Create Folder : No  -   Path: /shares/share2

Maybe start with a single /shares volume than you can add more.

**Cleanup** 

Stop everything with:

 ```
docker-compose stop
docker-compose rm
```

On server machine :

```
rm -rf /mnt/ssd1/misc/unison_data/server
mkdir -p /mnt/ssd1/misc/unison_data/server
```

On client machine :
```
rm -rf ./local_tests/client
mkdir -p ./local_tests/client
```

**Troubleshooting :**

So if you get sync was interrupted it means key exchange is ok now and client key is now on server authorized_keys.
You can test connectivity manually inside the docker container.

From the client machine try to run unison sync manually :
Basically run unison passing default profile name unicloud

```
docker-compose exec test_unicloud_client /bin/bash   
su - unison
unison unicloud
```

If you get the same error there must be a network issue between the client and the server.
Check that path/port are correct on unison profile /data/.unison/unicloud.prf

An example profile should look like this :

```
root=ssh://unison@unicloud_server:22//shares/share1
root=/data/share
clientHostName=testing-client1
batch = true
auto = true
prefer = newer
log = false
#place additional params with UNISON_PARAMS env
ignore = Name .git*
```

Make sure paths are correct.
If not maybe it's something wrong with the share/volumes path.


If you want to remove just the client you can remove it from the UI.
Client page use the tools icon to manage clients "/clients/mgt"

<img width="978" alt="image" src="https://user-images.githubusercontent.com/2765876/151140160-7eb28065-ebe3-4aa6-8419-750838380415.png">

If you remove a client and then you plan to register again make sure you delete the data folder like I suggested above.

```
rm -rf ./local_tests/client
mkdir -p ./local_tests/client
```

I hope you can fix with a clean config :-)

Let me know how I can make the doc better if something is unclear.
