### ISSUE TITLE
NOOB Client - Server Two  Machines LAN Idiots Guide

### ISSUE THREAD

**Issue by robbudge** [agarbato/unicloud#36]
Love the application and looks like it  will be a great help. 
But from a complete noob,
I have 2 Machines 192.167.1.4 and 192.167.1.11
I am looking for an  example Client (192.167.1.4) and server (192.167.1.11).
I have docker installed and running  the sever on  192.167.1.11 with the network set to bridge.
on 192.167.1.4 i have  the client  running with the network set to bridge and the server host set to the IP.
but still nothing.
Is  there  a basic compose file for the  two individual machines that i can look over ?

**Comment by agarbato** [comment]
Hi,

Thanks for testing the app.
I will include some additional compose on the doc.
In the meantime this should work for you.

Server compose.
Change volumes bind according to your setup.
As explained on the readme you need 2 volumes.
One is the data folder, the other is the share folder.
Source path can be absolute (/home/myuser/myserverdatafolder) or relative (./data) and can be anything where your user can rw.
 
```
version: '3.3'
services:
  # SERVER
  unicloud_server:
    image: agarbato1/unison-unicloud
    ports:
      - "2222:22"
      - "5001:80"
    environment:
      - USER=unison
      - USER_UID=1000
      - SERVER_HOSTNAME=unicloud_server
      - SERVER_UI_USERNAME=admin
      - SERVER_UI_PASSWORD=abcd12345
      - SERVER_DEBUG=True
      - ROLE=SERVER
    networks:
      unison:
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./shares
        target: /shares
networks:
  unison:
    driver: bridge
    ipam:
      driver: default
```

Client.
Notice here you need to use exposed ports from the server.
5001 for api, 2222 for SSH server. Those are the default as normally port 22 and 80 are used by other services.
You can change them but make sure they match between client and server.
If you can use an hostname for the server would be better must the client must be able to resolve its name.

```
version: '3.3'
services:
  # CLIENT
  unicloud_client:
    image: agarbato1/unison-unicloud
    environment:
      - CLIENT_HOSTNAME=testing-client1
      - ROLE=CLIENT
      - USER=unison
      - USER_UID=1000
      - SERVER_HOSTNAME=192.167.1.11
      - SERVER_PORT=2222
      - SERVER_SHARE=share1
      - SHARE_IGNORE=.git*|.idea|.unison|.DS_Store
      - API_PROTOCOL=http
      - API_PORT=5001
      - SYNC_INTERVAL=120
    restart: on-failure
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./share
        target: /data/share
    networks:
      unison:
networks:
  unison:
    driver: bridge
    ipam:
      driver: default
```

Once the server is up you should be able to reach the UI from a browser at[192.167.1.11:5001](http://192.167.1.11:5001)
Follow the rest of the guide to activate your client and define a share.
Follow troubleshooting section if you still have issues.
Thanks
Andrea
